apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
data:
  ENVIRONMENT: staging
  CLUSTER_NAME: kind-flux-staging
  CLUSTER_DOMAIN: staging.example.com
