apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  dependsOn:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: alerts.notification.toolkit.fluxcd.io
  resources:
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Provider
      metadata:
        name: github-status
        namespace: flux-system
      spec:
        type: github
        address: https://github.com/vtmocanu/flux-fleet
        secretRef:
          name: github-auth
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Alert
      metadata:
        name: github-status
        namespace: flux-system
      spec:
        providerRef:
          name: github-status
        eventSources:
          - kind: Kustomization
            name: flux-system
# ceva
