apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cert-manager-chart
spec:
  interval: 1h
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    tag: v1.17.2 # {"$imagepolicy": "infra:cert-manager:tag"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  releaseName: cert-manager
  chartRef:
    kind: OCIRepository
    name: cert-manager-chart
  values:
    installCRDs: true
